Auto ingest
WatchBeam/ftl-sdk pull request #58
Opened 2017-04-18 22:17 UTC by dhkamra-microsoft

Added an api to find the closest ingest server from a list of ingest servers. I have put it in ftl so any client that doesn't support curl can use it

2017-04-22 04:27 UTC, QuinnDamerell-MS requested changes
Looks good overall, just a few little things. Thanks for the commit!

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +ftl_status_t ftl_find_closest_ingest(const char* ingestIps[], const char* ingestNames[], int ingestsCount, char* bestIngestIpComputed)
I don't think this is used, so you might not need to pass it.

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +    {
nit: keep on same line as for

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +        ingestElement[i].rtt = 500;
might want to default this higher

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +    ftl_ingest_t* ingestElement;
nit: elements

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +    OS_THREAD_HANDLE *handle;
nit: handles

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +    OS_THREAD_HANDLE *handle;
Actually, you could even add this to the thread_data below to make it a little cleaner.

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +        os_create_thread(&handle[i], NULL, _ingest_get_rtt, &data[i]);
can this fail? if so should you abort?

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +
free(ingestElement)

2017-04-22 04:27 UTC, QuinnDamerell-MS commented on libftl/ingest.c
> +
well, do this before and after the return above

2017-04-24 17:30 UTC, dhkamra-microsoft commented on libftl/ingest.c
> +        ingestElement[i].rtt = 500;
Using the same value as ftl uses inside _ingest_get_hosts.

2017-04-24 17:35 UTC, dhkamra-microsoft commented on libftl/ingest.c
> +        os_create_thread(&handle[i], NULL, _ingest_get_rtt, &data[i]);
Using the same logic as _ingest_get_hosts. I think its ok. Even if one of the threads fail, you can still recover. Although a thread creation failure probably means something much more malign.

2017-04-24 21:25 UTC, dhkamra-microsoft reviewed
Made changes as per quinn's comments. Added one small api after conferring with Stefan.

2017-05-17 23:40 UTC, merged