bitrate update stable
WatchBeam/ftl-sdk pull request #59
Opened 2017-07-07 19:46 UTC by dhkamra-microsoft

Adaptive bitrate thread. 
The idea is to have the client to initiate the thread on the sdk, and the thread makes callback to the client to tell them what bandwidth to set.
Incorporating rtt is not well done and is a TODO item.

2017-07-11 22:58 UTC, fylock commented on libftl/ftl_private.h
> +    uint64_t ullInitialEncodingBitrate;
ull?

2017-07-11 23:00 UTC, dhkamra-microsoft commented on libftl/ftl_private.h
> +    uint64_t ullInitialEncodingBitrate;
Hungarian notation. Unsigned Long Long.

2017-07-11 23:02 UTC, dhkamra-microsoft commented on libftl/ftl_private.h
> +    uint64_t ullInitialEncodingBitrate;
Actually I will remove all Hungarian notation to keep it consistent with rest of ftl. Added TODO item.

2017-07-12 02:05 UTC, fylock commented on libftl/media.c
> +        )
nit: extra line

2017-07-20 18:17 UTC, fylock commented on libftl/media.c
> +                    // We had to lower bitrate. Bitrate is not stable.
Not sure how this compiled for you. This should be FTL_BANDWIDTH_CONSTRAINED

2017-07-20 18:18 UTC, fylock requested changes

2017-07-20 18:18 UTC, fylock commented on libftl/media.c
> +                    uint64_t recommended_bitrate = compute_recommended_bitrate(current_encoding_bitrate, UPGRADE_EXCESSIVE);
FTL_UPGRADE_EXCESSIVE

2017-07-27 18:19 UTC, fylock approved these changes

2017-08-09 18:42 UTC, sslivins approved these changes

2017-08-09 18:42 UTC, sslivins commented on libftl/ftl_private.h
> +    BOOL(*change_bitrate_callback)(void*, uint64_t);
is it possible to use the existing status callback?...it would be simpler for those that have already implemented our sdk to simply add another switch case for handle upgrade/downgrade msgs

2017-08-09 18:42 UTC, sslivins commented on libftl/ftl_private.h
> +#define MAX_SUPPORTED_BITRATE_BPS 5000000 // 5*1000*1000
we allow people to stream at 10mbps and higher so i dont want a cap

2017-08-09 18:42 UTC, sslivins commented on libftl/media.c
> +        recommended_bitrate = MAX_SUPPORTED_BITRATE_BPS;
we shouldnt have a hardcoded max bitrate

2017-08-09 18:44 UTC, sslivins commented
gtg, i'll fix the linux build after the merge

2017-08-09 18:44 UTC, merged